#!/usr/bin/python3
# SPDX-HileCopyrightText: 2023 Atsuya Morita
#SPDX-License-Identifier: BSD-3-Cluse

import sys

def tonum(s):
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            print("Invalid input: not a number", file=sys.stderr)
            sys.exit(1)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
